# Generated by Django 3.2.5 on 2021-08-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
